project:
  type: website
  output-dir: docs
  resources: ResumeF26.pdf

website:
  description: "Molly Lingenfelter"
  site-url: https://mollylingenfelter.github.io # you must change this appropriately for RSS feeds to work properly
  title: "Molly Lingenfelter"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

